server:
  port: 4004 # gateway listens on port 4004

spring:
  cloud:
    gateway:
      routes:

        # REST CLIENT -> http://localhost:4004/auth/login
        # API GATEWAY -> http://auth-service:4005/login
        - id: auth-service-route
          uri: http://auth-service:4005 # address of service in Docker container
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1

        # route for CRUD operation endpoints
        # REST CLIENT -> https://localhost:4004/api/patients
        # API GATEWAY -> http://patient-service:4000/patients
        # PATIENT SERVICE (SPRING BOOT APP) -> /patients -> Patients Array
        - id: patient-service-route
          uri: http://patient-service:4000
          predicates:
            - Path=/api/patients/**
          filters:
            - StripPrefix=1
            - JwtValidation # Spring will look for a class suffixed with GatewayFilterFactory

        # route for API docs endpoint
        # REST CLIENT -> http://localhost:4004/api-docs/patients
        # API GATEWAY -> http://patient-service:4000/v3/api-docs
        - id: api-docs-patient-route
          uri: http://patient-service:4000
          predicates:
            - Path=/api-docs/patients
          filters:
            - RewritePath=/api-docs/patients, /v3/api-docs
        - id: api-docs-auth-route
          uri: http://auth-service:4005
          predicates:
            - Path=/api-docs/auth
          filters:
            - RewritePath=/api-docs/auth, /v3/api-docs